# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: northwind
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  php:
    build:
      context: ./php
    restart: always
    volumes:
      - ./php/wwwroot:/var/www/html
    ports:
      - "9080:80"
    depends_on:
      - db
    tty: true
    stdin_open: true

  python:
    build:
      context: ./python
    #volumes:
    #  - ./php:/var/www/html
    ports:
      - "10080:10080"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      API_USER: Stefano

#  java:
#    build:
#      context: ./java
#    ports:
#      - "10000:8080"
#    depends_on:
#      - db
#    tty: true
#    stdin_open: true
#    profiles:
#      - java

volumes:
  pgdata: